name: Gen Forks List - CloudEngineHub

run-name: Gen Forks List - CloudEngineHub

on:
  schedule:
    - cron: "0 1 * * 1,4" # Run every monday and thursday at 1:00 AM
  workflow_dispatch: # Manual dispatch

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

defaults:
  run:
    shell: bash
    working-directory: ./scripts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gen-forks-list:
    name: Gen Forks List
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      
      - name: Configure git
        run: |
          git config --global user.name "github-actions[JadeCong-bot]"
          git config --global user.email "github-actions[JadeCong-bot]@users.noreply.github.com"
      
      - name: Run script gen-forks-list
        run: echo "CloudEngineHub" | ./gen-forks-list.sh
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: Commit changes
        run: |
          cd ..
          git add .
          git commit -m "Update Forks List for CloudEngineHub" || exit 0
      
      - name: Push changes
        run: git push
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
