name: Update Readme

run-name: Update Readme

on:
  schedule:
    - cron: "0 0 * * 1,4" # Run every monday and thursday at 0:00 AM
  workflow_dispatch: # Manual dispatch

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-readme:
    name: Update Readme for JadeCong
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository to the runner
        uses: actions/checkout@v4
      
      - name: Checkout target repository to the runner
        uses: actions/checkout@v4
        with:
          repository: JadeCong/JadeCong.github.io
          path: JadeCong.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install -r scripts/requirements.txt
      
      - name: Update readme
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update-readme.py
          git status
          cat README.md
      
      # - name: Commit files
      #   run: |
      #     git config --global user.name "github-actions[JadeCong-bot]"
      #     git config --global user.email "github-actions[JadeCong-bot]@users.noreply.github.com"
      #     git commit -a -m "Update readme for JadeCong" || exit 0
      
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
